### ISSUE TITLE
Usage of Backend API with Websockets.

### ISSUE THREAD

**Issue by peculiarity** [OasisDEX/oasis-react#19]
#There was this discussion started about whether it's good idea to start using  backend service with Websocket channel for communication. The idea is to relieve the client from all the burden to communicate directly with the blockchain. This  will improve UX in cases where we would like to get historical data.

Of course this could be extended for all of the operations. Placing orders , getting notification for filled orders and etc.

Let's discuss this idea here  and come to a conclusion.

@pimato @deepinit-arek

**Comment by NiklasKunkel** [comment]
This is on my roadmap for the Oasis API.

Basically an async process tracking event logs coming from the Oasis contract and updating a database to be completely in sync with the contract (current orderbook) + extra data (trade history). Then when a user queries the API (or in your case the front-end) it will pull data from the db, rather than having to make multiple calls to the blockchain client (doesn't scale). However, as a first iteration it would be much simpler to build this as HTTP first rather than a WS pushing notifications.

From my stress testing so far, using the poor-man's solution of calling the client each time the API holds up pretty well. I'd like to implement this in the future but it takes a backseat to the work I want to do on Oracles in the short term.

We should get on a call early next week to discuss what the requirements would be for the front-end.
